name: redpharmabd_app
description: "RedPharmaBD: Your trusted online pharmacy app for ordering medicines, health products, and wellness essentials with convenience and reliability."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.0
  animated_splash_screen: ^1.3.0
  cupertino_icons: ^1.0.8
  http: ^1.1.0
  font_awesome_flutter: ^10.7.0
  provider: ^6.0.5
  flutter_slidable: ^3.1.0
  connectivity_plus: ^4.0.1
  shared_preferences: ^2.3.2
  image_picker: ^1.0.7
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  google_fonts: ^6.2.1
  intl: ^0.19.0
  lottie: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/default_user.png
    - assets/images/redpharma-icon.png
    - assets/images/banners/
    - assets/images/categories/
    - assets/images/products/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/redpharma-icon.png"